### ISSUE TITLE
add doc for API editLog

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#429]
/editLog/model
/editLog/model?itemID=idmongo&whoID=id&isariLab=id&isariRole=value&startDate=2017-03-05&endDate=2017-05-08&path=value&accessMonitoring=value&action=value&activityType=value&limit=20&skip=250

## API args directly binded to editLog Object : 
- [x] model : 'People', 'Activity' or 'Organization' **mandatory**
- [x] itemID : mongo ID
- [x] whoID : mongo ID
- [x] startDate : iso format YYYY-MM-DD
- [x] endDate : iso format YYYY-MM-DD
- [x] action : 'create', 'delete' or 'update'
- [x] path : diff.path when action = 'update', data otherwise

## API args pointing to isariAuthorizedCenters
- [x] isariLabID :  isariAuthorizedCenters.organization mongoID
- [x] isariRole : isariAuthorizedCenters.role

## accesMonitoring Filter
- [ ] accesMonitoring: Value of accessMonitroing fields from schemas.
Fecth list of paths from schemas then filter on diff.path or data in editLog objects.

## pagination
- [x] limit 
- [x] skip
- [x] count : if set this parameter will make the api to return the number of results. It automatically discard skip and limit parameter if it exist

## TODO later 
- [ ] activityType : type field in Activity objects 

## data returned

response header might contain a fastforward parameter to warn the client to skip edits which were added to the response in place of filtered out edits

```json
[{
 "who" : {
     id: "mongo id",
     'name': "firstname Name" ,
     'roles': [{
          "lab" : "organization acronym or name",
          "role" : "role"
   }]},
 "date" : "YYYY-MM-DD hh:mm",
 "item" : {
      "id": "mongo id",
      "name" : "name"
 },
 "action" : "update",
 "paths" : [
      {   "path": "fieldname",
          "valueBefore": {**value object ?**},
          "valueAfter": {**value object ?**},
          "accessMonitoring" : "" // should be handled in client as enums ?,
          "editType" : "update" | "delete" | "create"
      }]
}]
```
## Example of one editlog object stored in mongo
See https://github.com/flitbit/diff#differences for diff format.

```json
{
    "_id" : ObjectId("5898399c07f86e00018a614e"),
    "model" : "People",
    "item" : ObjectId("589488a211d0d100381bdf47"),
    "date" : ISODate("2017-02-06T08:53:48.727Z"),
    "action" : "update",
    "who" : "sophie.jacquot",
    "diff" : [ 
        [ 
            {
                "kind" : "E",
                "path" : [ 
                    "latestChangeBy"
                ],
                "lhs" : "IMPORT",
                "rhs" : "sophie.jacquot"
            }
        ], 
        [ 
            {
                "kind" : "E",
                "path" : [ 
                    "academicMemberships", 
                    0, 
                    "organization", 
                    "id", 
                    "11"
                ],
                "lhs" : 153,
                "rhs" : 157
            }
        ], 
        [ 
            {
                "kind" : "D",
                "path" : [ 
                    "academicMemberships", 
                    0, 
                    "endDate"
                ],
                "lhs" : "2013"
            }
        ], 
        [ 
            {
                "kind" : "A",
                "path" : [ 
                    "academicMemberships"
                ],
                "index" : 1,
                "item" : {
                    "kind" : "D",
                    "lhs" : {
                        "organization" : ObjectId("5894889a11d0d100381bcc9d"),
                        "startDate" : "2014",
                        "membershipType" : "membre"
                    }
                }
            }
        ]
    ],
    "__v" : 0
}
```
